# Generated by Django 4.2.13 on 2024-07-24 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addtitle', models.CharField(default='', max_length=200)),
                ('Brand', models.CharField(default='', max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('Location', models.CharField(default='', max_length=200)),
                ('Discription', models.TextField(default='')),
                ('Year', models.PositiveIntegerField(default='')),
                ('Phone', models.CharField(default='', max_length=15)),
                ('Images', models.ImageField(default='', upload_to='products/')),
                ('State', models.CharField(default='', max_length=100)),
                ('District', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addtitle', models.CharField(default='', max_length=200)),
                ('Brand', models.CharField(default='', max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('Location', models.CharField(default='', max_length=200)),
                ('Discription', models.TextField(default='')),
                ('Year', models.PositiveIntegerField(default='')),
                ('Phone', models.CharField(default='', max_length=15)),
                ('Images', models.ImageField(default='', upload_to='products/')),
                ('State', models.CharField(default='', max_length=100)),
                ('District', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Dob', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='olx.login')),
            ],
        ),
    ]
