# Generated by Django 4.2.13 on 2024-07-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_product_sell_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sell',
            name='Fk',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='Product_view', to='olx.product_view'),
        ),
    ]
